name: Test and Build App

on:
  push:
    branches:
      - main   # change to master if your repo uses master
    paths:
      - "**/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      # Run linting
      - name: Run linting tests
        run: |
          flake8 --ignore=E501,F401

      # Login to Docker Hub
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Generate version tag
      - name: Set Docker tag
        run: |
          VERSION=v$(date +"%Y%m%d%H%M%S")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Build Docker image
      - name : Build Docker images
        run: |
          docker build . -t hagersaad329/repo-test:${{ env.VERSION }}
      #  Push Docker image
      - name: push docker images
        run : |
          docker push hagersaad329/repo-test:${{ env.VERSION }}
      # update k8s manifest files
      - name : update the manifest files
        run: |
          cat deploy/deployment.yaml
          sed -i "s|hagersaad329/repo-test:.*|hagersaad329/repo-test:${{ env.VERSION }}|g" deploy/deployment.yaml
          cat deploy/deployment.yaml
      # Update Github
      - name: Commit the changes
        run: |
          git config --global user.email "<>"
          git config --global user.name "GitHub Actions Bot"
          git add deploy/deployment.yaml
          git commit -m "Update deployment.yaml with new image version - ${{ env.VERSION }}"
          git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com:Hager-Saad-2024/Flask-App-GitHub-Actions-ArgoCD-Public.git
          git push origin master